version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=elections
      - MYSQL_ROOT_PASSWORD=mysqlPW
      - MYSQL_ROOT_HOST=% 
    ports:
      - '3306:3306'
    volumes:
      - ./sql/model.sql:/docker-entrypoint-initdb.d/model.sql